// SPDX-License-Identifier: MPL-2.0
import { assessAdapterVersionCompatibility, type AdapterVersionPolicy } from "./adapter-contract.js";
import type { ValidationResult } from "./index.js";
import { measureBoundedJson } from "./resource-accounting.js";
import { resolveFreshnessState, validateAndMeasureReadOnlyRepresentation, type ReadOnlyEntry, type ReadOnlyRepresentation, type ReadOnlyRepresentationPolicy, type ReadOnlyRepresentationUsage } from "./representation.js";
import { COMPANION_PROTOCOL_VERSION, companionIssue, isCompanionToken, makeCompanionCursor, parseCompanionCursor, parseCompanionRequest, requestFailureCode, resolveCompanionPolicy, type BeginCompanionPageWorkResult, type CompanionCodeResult, type CompanionConversationMetadata, type CompanionEntryView, type CompanionFailureCode, type CompanionNavigationResult, type CompanionPolicy, type CompanionRequest, type CompanionResponse, type CompanionSearchResult, type CompanionTimelinePage, type CompanionUsage, type DeliveredCompanionResponse, type PendingCompanionPageWork, type SyntheticCompanionSource } from "./companion-protocol.js";

type ReadySource = Readonly<{ status: "ready"; conversationId: string; label?: string; representation: ReadOnlyRepresentation; usage: ReadOnlyRepresentationUsage; adapterPolicy: AdapterVersionPolicy; byId: ReadonlyMap<string, ReadOnlyEntry> }>;
type Source = ReadySource | Readonly<{ status: "invalid"; conversationId: string; label?: string; reason: CompanionFailureCode }>;
type Session = { id: string; generation: number; active?: string; pages: Set<string>; search: CompanionSearchResult[]; code?: CompanionCodeResult; pending: Set<string>; last: number };
type ResidentPage = { key: string; sessionId: string; conversationId: string; bytes: number; last: number };

function sourceReason(code?: string): CompanionFailureCode { return code === "private-content-disabled" ? "source-private-disabled" : "source-corrupt"; }
function text(value: string | undefined, max: number): { value?: string; truncated: boolean } { if (value === undefined) return { truncated: false }; return value.length <= max ? { value, truncated: false } : { value: value.slice(0, max), truncated: true }; }
function view(entry: ReadOnlyEntry, p: CompanionPolicy): CompanionEntryView { const body = text(entry.text, p.maxEntryTextCodeUnits); return Object.freeze({ id: entry.id, parentId: entry.parentId, childIds: Object.freeze(entry.childIds.slice(0, p.maxChildIdsPerEntry)), sequence: entry.sequence, kind: entry.kind, ...(entry.label ? { label: entry.label } : {}), ...(body.value !== undefined ? { text: body.value } : {}), textTruncated: body.truncated, codeBlockCount: entry.codeBlocks.length, codeLanguages: Object.freeze(entry.codeBlocks.slice(0, p.maxChildIdsPerEntry).map((block) => block.language ?? null)), ...(entry.jumpBackReference ? { jumpBackReference: entry.jumpBackReference } : {}) }); }
function meta(source: ReadySource, now: number): CompanionConversationMetadata { return Object.freeze({ conversationId: source.conversationId, ...(source.label ? { label: source.label } : {}), adapter: Object.freeze({ ...source.representation.adapter }), freshness: resolveFreshnessState(source.representation.provenance.freshness, now), entryCount: source.representation.entries.length, activeEntryId: source.representation.activePath.at(-1) ?? null }); }
function findSnippet(entry: ReadOnlyEntry, needle: string, max: number): { snippet: string; truncated: boolean } | null { for (const value of [entry.label, entry.text, ...entry.codeBlocks.map((block) => block.text)].filter((item): item is string => typeof item === "string")) { const at = value.toLocaleLowerCase().indexOf(needle); if (at < 0) continue; if (value.length <= max) return { snippet: value, truncated: false }; const start = Math.max(0, Math.min(at - Math.floor(max / 3), value.length - max)); return { snippet: value.slice(start, start + max), truncated: true }; } return null; }

export class SyntheticCompanion {
  readonly #policy: CompanionPolicy; readonly #representationPolicy?: Partial<ReadOnlyRepresentationPolicy>;
  readonly #sources = new Map<string, Source>(); readonly #sessions = new Map<string, Session>(); readonly #revoked = new Set<string>(); readonly #pages = new Map<string, ResidentPage>();
  #clock = 0; #work = 0;
  constructor(sources: readonly SyntheticCompanionSource[] = [], options: { policy?: Partial<CompanionPolicy>; representationPolicy?: Partial<ReadOnlyRepresentationPolicy> } = {}) { this.#policy = resolveCompanionPolicy(options.policy); this.#representationPolicy = options.representationPolicy; for (const source of sources) this.upsertSource(source); }
  get policy(): CompanionPolicy { return this.#policy; }

  upsertSource(source: SyntheticCompanionSource): ValidationResult<CompanionConversationMetadata> {
    try {
      if (!isCompanionToken(source.conversationId) || (source.label !== undefined && (typeof source.label !== "string" || source.label.length > 512))) return { ok: false, issues: [companionIssue("$", "invalid-companion-source", "Invalid source identity.")] };
      if (this.#sources.has(source.conversationId)) this.#releaseConversation(source.conversationId);
      const validated = validateAndMeasureReadOnlyRepresentation(source.representation, this.#representationPolicy);
      if (!validated.ok) { this.#sources.set(source.conversationId, Object.freeze({ status: "invalid", conversationId: source.conversationId, ...(source.label ? { label: source.label } : {}), reason: sourceReason(validated.issues[0]?.code) })); return validated; }
      if (!validated.value.representation.provenance.synthetic) { this.#sources.set(source.conversationId, Object.freeze({ status: "invalid", conversationId: source.conversationId, ...(source.label ? { label: source.label } : {}), reason: "source-private-disabled" })); return { ok: false, issues: [companionIssue("$.representation.provenance.synthetic", "private-content-disabled", "Synthetic records only.")] }; }
      const compatibility = assessAdapterVersionCompatibility(validated.value.representation.adapter, source.adapterPolicy);
      if (!compatibility.compatible) { this.#sources.set(source.conversationId, Object.freeze({ status: "invalid", conversationId: source.conversationId, ...(source.label ? { label: source.label } : {}), reason: compatibility.reason })); return { ok: false, issues: [companionIssue("$.representation.adapter", compatibility.reason, "Adapter is incompatible.")] }; }
      const representation = validated.value.representation; const ready: ReadySource = Object.freeze({ status: "ready", conversationId: source.conversationId, ...(source.label ? { label: source.label } : {}), representation, usage: validated.value.usage, adapterPolicy: Object.freeze({ ...source.adapterPolicy }), byId: new Map(representation.entries.map((entry) => [entry.id, entry])) }); this.#sources.set(source.conversationId, ready); return { ok: true, value: meta(ready, representation.provenance.capturedAt), warnings: [] };
    } catch { return { ok: false, issues: [companionIssue("$", "companion-source-inspection-failed", "Source inspection failed safely.")] }; }
  }
  removeSource(id: string): boolean { const deleted = this.#sources.delete(id); if (deleted) this.#releaseConversation(id); return deleted; }

  dispatch(input: unknown, now = Date.now()): DeliveredCompanionResponse {
    const parsed = parseCompanionRequest(input, this.#policy); if (!parsed.ok) return this.#deliver({ version: 1, requestId: "invalid", sessionId: "invalid", operation: "invalid", generation: 0, ok: false, code: requestFailureCode(parsed.issues), usage: this.usage() });
    try { return this.#dispatch(parsed.value, now); } catch { return this.#failure(parsed.value, this.#sessions.get(parsed.value.sessionId)?.generation ?? 0, "internal-failure"); }
  }
  beginPageWork(input: unknown): BeginCompanionPageWorkResult {
    const parsed = parseCompanionRequest(input, this.#policy); if (!parsed.ok || parsed.value.operation !== "page") return { ok: false, delivered: this.dispatch(input) };
    const request = parsed.value; const session = this.#session(request); if ("response" in session) return { ok: false, delivered: session }; if (session.active !== request.conversationId) return { ok: false, delivered: this.#failure(request, session.generation, "conversation-closed") };
    const cursor = parseCompanionCursor(request.cursor); if (!cursor || cursor.generation !== session.generation) return { ok: false, delivered: this.#failure(request, session.generation, "cursor-invalid") }; if (session.pending.size >= this.#policy.maxPendingPageWork) return { ok: false, delivered: this.#failure(request, session.generation, "pending-limit") };
    const work = Object.freeze({ workId: `work:${++this.#work}`, request, generation: session.generation }); session.pending.add(work.workId); return { ok: true, work };
  }
  completePageWork(work: PendingCompanionPageWork, now = Date.now()): DeliveredCompanionResponse { const session = this.#sessions.get(work.request.sessionId); if (!session || this.#revoked.has(work.request.sessionId) || !session.pending.delete(work.workId) || session.generation !== work.generation || session.active !== work.request.conversationId) return this.#failure(work.request, session?.generation ?? work.generation, "late-reply-discarded"); return this.#page(work.request, session, now); }

  usage(): CompanionUsage { let retainedSearchResults = 0, retainedCodeUnits = 0, pendingPageWork = 0, residentPageBytes = 0; const active = new Set<string>(); for (const session of this.#sessions.values()) { retainedSearchResults += session.search.length; retainedCodeUnits += session.code?.text.length ?? 0; pendingPageWork += session.pending.size; if (session.active) active.add(session.active); } for (const page of this.#pages.values()) residentPageBytes += page.bytes; return Object.freeze({ sessions: this.#sessions.size, revokedSessions: this.#revoked.size, activeConversations: active.size, residentPages: this.#pages.size, residentPageBytes, retainedSearchResults, retainedCodeUnits, pendingPageWork }); }

  #dispatch(request: CompanionRequest, now: number): DeliveredCompanionResponse {
    const result = this.#session(request); if ("response" in result) return result; const session = result; session.last = ++this.#clock; if (this.#revoked.has(session.id) && request.operation !== "revoke") return this.#failure(request, session.generation, "session-revoked");
    switch (request.operation) {
      case "list": return this.#list(request, session, now); case "open": return this.#open(request, session, now); case "page": return this.#page(request, session, now); case "entry": return this.#entry(request, session, now); case "code": return this.#code(request, session, now); case "search": return this.#search(request, session, now); case "navigate": return this.#navigate(request, session, now);
      case "status": return this.#success(request, session, Object.freeze({ activeConversationId: session.active ?? null }));
      case "close": this.#clear(session); session.generation += 1; return this.#success(request, session, Object.freeze({ closed: true }));
      case "revoke": { this.#clear(session); session.generation += 1; this.#revoked.add(session.id); while (this.#revoked.size > this.#policy.maxRevokedSessions) { const first = this.#revoked.values().next().value as string | undefined; if (!first) break; this.#revoked.delete(first); } this.#sessions.delete(session.id); return this.#deliver({ version: 1, requestId: request.requestId, sessionId: request.sessionId, operation: "revoke", generation: session.generation, ok: true, stale: false, data: Object.freeze({ revoked: true }), usage: this.usage() }); }
    }
  }
  #session(request: CompanionRequest): Session | DeliveredCompanionResponse { const found = this.#sessions.get(request.sessionId); if (found) return found; if (this.#revoked.has(request.sessionId)) return this.#failure(request, 0, "session-revoked"); if (this.#sessions.size >= this.#policy.maxSessions) { const victim = [...this.#sessions.values()].filter((value) => !value.active && !value.pages.size && !value.pending.size).sort((a, b) => a.last - b.last || a.id.localeCompare(b.id))[0]; if (victim) this.#sessions.delete(victim.id); } if (this.#sessions.size >= this.#policy.maxSessions) return this.#failure(request, 0, "session-limit"); const session: Session = { id: request.sessionId, generation: 1, pages: new Set(), search: [], pending: new Set(), last: ++this.#clock }; this.#sessions.set(session.id, session); return session; }
  #source(request: CompanionRequest & { conversationId: string }, now: number): ReadySource | DeliveredCompanionResponse { const source = this.#sources.get(request.conversationId); const generation = this.#sessions.get(request.sessionId)?.generation ?? 0; if (!source) return this.#failure(request, generation, "conversation-missing"); if (source.status === "invalid") return this.#failure(request, generation, source.reason); const compatibility = assessAdapterVersionCompatibility(source.representation.adapter, source.adapterPolicy); if (!compatibility.compatible) return this.#failure(request, generation, compatibility.reason); if (resolveFreshnessState(source.representation.provenance.freshness, now) === "expired") return this.#failure(request, generation, "source-expired"); return source; }
  #list(request: Extract<CompanionRequest, { operation: "list" }>, session: Session, now: number): DeliveredCompanionResponse { const conversations: CompanionConversationMetadata[] = []; for (const source of [...this.#sources.values()].sort((a, b) => a.conversationId.localeCompare(b.conversationId))) { if (source.status !== "ready" || resolveFreshnessState(source.representation.provenance.freshness, now) === "expired") continue; conversations.push(meta(source, now)); if (conversations.length >= request.limit) break; } return this.#success(request, session, Object.freeze({ conversations: Object.freeze(conversations) })); }
  #open(request: Extract<CompanionRequest, { operation: "open" }>, session: Session, now: number): DeliveredCompanionResponse { const source = this.#source(request, now); if ("response" in source) return source; this.#clear(session); session.generation += 1; session.active = request.conversationId; session.last = ++this.#clock; this.#enforceConversations(request.conversationId); const active = source.representation.activePath.at(-1); const index = active ? source.representation.entries.findIndex((entry) => entry.id === active) : 0; const delivered = this.#storePage(request, session, source, Math.max(0, index - Math.floor(request.limit / 2)), request.limit, now); if (!delivered.response.ok) { const code = delivered.response.code; this.#clear(session); session.generation += 1; return this.#failure(request, session.generation, code); } return delivered; }
  #page(request: Extract<CompanionRequest, { operation: "page" }>, session: Session, now: number): DeliveredCompanionResponse { if (session.active !== request.conversationId) return this.#failure(request, session.generation, "conversation-closed"); const cursor = parseCompanionCursor(request.cursor); if (!cursor || cursor.generation !== session.generation) return this.#failure(request, session.generation, "cursor-invalid"); const source = this.#source(request, now); if ("response" in source) return source; const start = request.direction === "before" ? Math.max(0, cursor.start - request.limit) : Math.min(source.representation.entries.length, cursor.start + request.limit); return this.#storePage(request, session, source, start, request.limit, now); }
  #storePage(request: Extract<CompanionRequest, { operation: "open" | "page" }>, session: Session, source: ReadySource, start: number, limit: number, now: number): DeliveredCompanionResponse { const entries = source.representation.entries.slice(start, start + limit).map((entry) => view(entry, this.#policy)); const page: CompanionTimelinePage = Object.freeze({ conversation: meta(source, now), entries: Object.freeze(entries), ...(start > 0 ? { beforeCursor: makeCompanionCursor(session.generation, start) } : {}), ...(start + entries.length < source.representation.entries.length ? { afterCursor: makeCompanionCursor(session.generation, start) } : {}) }); const measured = measureBoundedJson(page, { maxNodes: this.#policy.maxResponseNodes, maxSerializedBytes: this.#policy.maxResidentPageBytes, maxStringCodeUnits: Math.max(this.#policy.maxEntryTextCodeUnits, this.#policy.maxCodeBlockTextCodeUnits) }); if (!measured.ok) return this.#failure(request, session.generation, "page-limit"); if (measured.value.serializedBytes > this.#policy.maxAggregateResidentPageBytes) return this.#failure(request, session.generation, "aggregate-page-limit"); const key = `${session.id}:${session.generation}:${source.conversationId}:${start}`; this.#removePage(key); while (this.#pages.size >= this.#policy.maxResidentPages || this.usage().residentPageBytes + measured.value.serializedBytes > this.#policy.maxAggregateResidentPageBytes) { const victim = [...this.#pages.values()].sort((a, b) => a.last - b.last || a.key.localeCompare(b.key))[0]; if (!victim) return this.#failure(request, session.generation, "aggregate-page-limit"); this.#removePage(victim.key); } this.#pages.set(key, { key, sessionId: session.id, conversationId: source.conversationId, bytes: measured.value.serializedBytes, last: ++this.#clock }); session.pages.add(key); const delivered = this.#success(request, session, page, resolveFreshnessState(source.representation.provenance.freshness, now) === "stale"); if (!delivered.response.ok) this.#removePage(key); return delivered; }
  #readyOperation(request: CompanionRequest & { conversationId: string }, session: Session, now: number): ReadySource | DeliveredCompanionResponse { if (session.active !== request.conversationId) return this.#failure(request, session.generation, "conversation-closed"); return this.#source(request, now); }
  #entry(request: Extract<CompanionRequest, { operation: "entry" }>, session: Session, now: number): DeliveredCompanionResponse { const source = this.#readyOperation(request, session, now); if ("response" in source) return source; const entry = source.byId.get(request.entryId); return entry ? this.#success(request, session, view(entry, this.#policy), resolveFreshnessState(source.representation.provenance.freshness, now) === "stale") : this.#failure(request, session.generation, "entry-missing"); }
  #code(request: Extract<CompanionRequest, { operation: "code" }>, session: Session, now: number): DeliveredCompanionResponse { const source = this.#readyOperation(request, session, now); if ("response" in source) return source; const entry = source.byId.get(request.entryId); const block = entry?.codeBlocks[request.blockIndex]; if (!block) return this.#failure(request, session.generation, "code-missing"); if (block.text.length > this.#policy.maxCodeBlockTextCodeUnits) return this.#failure(request, session.generation, "code-limit"); const value: CompanionCodeResult = Object.freeze({ entryId: entry!.id, blockIndex: request.blockIndex, ...(block.language ? { language: block.language } : {}), text: block.text }); const previous = session.code; session.code = value; const delivered = this.#success(request, session, value, resolveFreshnessState(source.representation.provenance.freshness, now) === "stale"); if (!delivered.response.ok) session.code = previous; return delivered; }
  #search(request: Extract<CompanionRequest, { operation: "search" }>, session: Session, now: number): DeliveredCompanionResponse { const source = this.#readyOperation(request, session, now); if ("response" in source) return source; const needle = request.query.trim().toLocaleLowerCase(); const values: CompanionSearchResult[] = []; for (const entry of source.representation.entries) { const found = findSnippet(entry, needle, this.#policy.maxSnippetCodeUnits); if (!found) continue; values.push(Object.freeze({ entryId: entry.id, sequence: entry.sequence, kind: entry.kind, snippet: found.snippet, snippetTruncated: found.truncated })); if (values.length >= request.limit) break; } const previous = session.search; session.search = values; const delivered = this.#success(request, session, Object.freeze({ results: Object.freeze(values) }), resolveFreshnessState(source.representation.provenance.freshness, now) === "stale"); if (!delivered.response.ok) session.search = previous; return delivered; }
  #navigate(request: Extract<CompanionRequest, { operation: "navigate" }>, session: Session, now: number): DeliveredCompanionResponse { const source = this.#readyOperation(request, session, now); if ("response" in source) return source; const entry = source.byId.get(request.entryId); if (!entry) return this.#failure(request, session.generation, "entry-missing"); const parent = entry.parentId ? source.byId.get(entry.parentId) ?? null : null; const siblings = parent ? parent.childIds.filter((id) => id !== entry.id) : []; if (entry.childIds.length + siblings.length > this.#policy.maxNavigationEntries) return this.#failure(request, session.generation, "navigation-limit"); const map = (ids: readonly string[]) => ids.map((id) => source.byId.get(id)).filter((value): value is ReadOnlyEntry => value !== undefined).map((value) => view(value, this.#policy)); const value: CompanionNavigationResult = Object.freeze({ entry: view(entry, this.#policy), parent: parent ? view(parent, this.#policy) : null, children: Object.freeze(map(entry.childIds)), siblings: Object.freeze(map(siblings)) }); return this.#success(request, session, value, resolveFreshnessState(source.representation.provenance.freshness, now) === "stale"); }

  #success(request: CompanionRequest, session: Session, data: unknown, stale = false): DeliveredCompanionResponse { return this.#deliver({ version: 1, requestId: request.requestId, sessionId: request.sessionId, operation: request.operation, generation: session.generation, ok: true, stale, data, usage: this.usage() }); }
  #failure(request: CompanionRequest, generation: number, code: CompanionFailureCode): DeliveredCompanionResponse { return this.#deliver({ version: 1, requestId: request.requestId, sessionId: request.sessionId, operation: request.operation, generation, ok: false, code, usage: this.usage() }); }
  #deliver(response: CompanionResponse): DeliveredCompanionResponse { const measured = measureBoundedJson(response, { maxNodes: this.#policy.maxResponseNodes, maxSerializedBytes: this.#policy.maxResponseSerializedBytes, maxStringCodeUnits: Math.max(this.#policy.maxCodeBlockTextCodeUnits, this.#policy.maxEntryTextCodeUnits) }); if (measured.ok) return Object.freeze({ response: Object.freeze(response), usage: measured.value }); const minimal: CompanionResponse = Object.freeze({ version: COMPANION_PROTOCOL_VERSION, requestId: response.requestId, sessionId: response.sessionId, operation: response.operation, generation: response.generation, ok: false, code: "response-limit", usage: this.usage() }); const fallback = measureBoundedJson(minimal, { maxNodes: 1_000, maxSerializedBytes: Math.max(4_096, this.#policy.maxResponseSerializedBytes), maxStringCodeUnits: 1_024 }); if (!fallback.ok) throw new RangeError("Minimal companion response exceeds policy."); return Object.freeze({ response: minimal, usage: fallback.value }); }
  #clear(session: Session): void { for (const key of [...session.pages]) this.#removePage(key); session.pages.clear(); session.search = []; session.code = undefined; session.pending.clear(); session.active = undefined; }
  #removePage(key: string): void { const page = this.#pages.get(key); if (!page) return; this.#pages.delete(key); this.#sessions.get(page.sessionId)?.pages.delete(key); }
  #releaseConversation(id: string): void { for (const session of this.#sessions.values()) if (session.active === id) { this.#clear(session); session.generation += 1; } }
  #enforceConversations(exclude: string): void { while (true) { const active = new Map<string, number>(); for (const session of this.#sessions.values()) if (session.active) active.set(session.active, Math.min(active.get(session.active) ?? Number.MAX_SAFE_INTEGER, session.last)); if (active.size <= this.#policy.maxResidentConversations) return; const victim = [...active.entries()].filter(([id]) => id !== exclude).sort((a, b) => a[1] - b[1] || a[0].localeCompare(b[0]))[0]; if (!victim) return; this.#releaseConversation(victim[0]); } }
}
